#!/usr/bin/python3

import sys
import os

files = sys.argv[1:]
#commit_note = sys.argv[1]

for i in files:
	os.system("git add {}".format(i))

commit_note = input("Commit note: ")

if commit_note == '':
	if len(files) == 1:
		os.system("git commit -am '{}'".format('update ' + files[0]))

	elif len(files) == 2:
		os.system("git commit -am '{}'".format("update {0} and {1}".format(files[0], files[1])))
	else:
		os.system("git commit -a")
else:
	os.system("git commit -am '{}'".format(commit_note))

print(commit_note)
os.system("git push")
